### ISSUE TITLE
Replace poetry with setuptools

### ISSUE THREAD

**Issue by ml31415** [limx0/betfair_parser#37]
It's several years now that pyproject.toml is the designated standard for python package metadata. Nevertheless, poetry seems [unwilling to adopt the standard definition](https://github.com/python-poetry/poetry/issues/3332) and insists on it's own entries in the file. This leads to ridiculous duplication, having all dependencies defined twice, project name defined twice, and so on. I'd suggest to ditch poetry completely and simply go with setuptools and setuptools-scm.

**Comment by limx0** [comment]
> This leads to ridiculous duplication, having all dependencies defined twice, project name defined twice, and so on

I have not experienced this, I don't bother filling out dependencies in my `[project]` section and my packages seem to install fine. 

I use poetry for all of my python projects and haven't had any issues with it so far. If there's something thats blocking you, I'm willing to give it a go (this is a very simple package and we don't really need poetry) but otherwise I'm hesitant to change without a reason.

**Comment by ml31415** [comment]
Nah, surely not a blocker, just a minor annoyance when updating dependencies. Let's leave it as is then.
