### ISSUE TITLE
Clean up handicap typing

### ISSUE THREAD

**Issue by limx0** [limx0/betfair_parser#47]
Seems like we have a `Handicap` proper type but are also using floats in quite a few places.

**Comment by ml31415** [comment]
Yeah ... I guess I initially went just with what betfair defines, even if it doesn't make much sense. I had set some range checks for Handicap ... just rechecked, in my test data I have a range from -700 to +300, so the range check would need some extension, maybe -1000 to +1000. If you know some better definition, let me know. The limits need to be super generous, otherwise we run into stupid parsing issues, which we can't handle gracefully.

**Comment by limx0** [comment]
Yep totally agree - this is in line with what I've seen so far. Thanks @ml31415 !
